CREATE DATABASE FASHION_AVENUE;
USE FASHION_AVENUE;
CREATE TABLE CATEGORY(
C_ID INT IDENTITY(1,1) PRIMARY KEY,
C_NAME VARCHAR(250)
);
CREATE TABLE ROLE(
R_ID INT IDENTITY(101,1) PRIMARY KEY,
R_NAME VARCHAR(250)
);
CREATE TABLE USER_RECORD(
U_ID INT IDENTITY(1001,1) PRIMARY KEY,
U_NAME VARCHAR(250),
U_EMAIL VARCHAR(250),
U_PASS VARCHAR(250),
U_ROLE_ID INT
FOREIGN KEY (U_ROLE_ID) REFERENCES ROLE(R_ID)
);
INSERT INTO USER_RECORD (U_NAME,U_EMAIL,U_PASS,U_ROLE_ID) VALUES ('Admin','admin@gmail.com','admin',101);

CREATE TABLE COUPON(
C_ID INT IDENTITY(1,1) PRIMARY KEY,
C_NAME VARCHAR(250),
C_DISCOUNT DECIMAL(18, 2)
);
CREATE TABLE USED_COUPON(
UC_ID INT PRIMARY KEY IDENTITY(10001,1),
UC_COUPON_ID INT
FOREIGN KEY (UC_COUPON_ID) REFERENCES COUPON(C_ID),
UC_USER_ID INT
FOREIGN KEY (UC_USER_ID) REFERENCES USER_RECORD(U_ID)
);

CREATE TABLE PRODUCT_COLOR(
PC_ID INT IDENTITY(1001,1) PRIMARY KEY,
PC_COLOR VARCHAR(250),
);

CREATE TABLE PRODUCT(
P_ID INT PRIMARY KEY IDENTITY(101,1),
P_NAME VARCHAR(250),
P_PRICE INT,
P_IMAGE VARCHAR(250),
P_COLOR INT
FOREIGN KEY (P_COLOR) REFERENCES PRODUCT_COLOR(PC_ID),
P_CATG_ID INT
FOREIGN KEY (P_CATG_ID) REFERENCES CATEGORY(C_ID),
);

CREATE TABLE PRODUCT_LIKE(
PL_ID INT IDENTITY(1001,1) PRIMARY KEY,
PL_COUNT INT,
PL_USER INT
FOREIGN KEY (PL_USER) REFERENCES USER_RECORD(U_ID),
PL_PROD_ID INT
FOREIGN KEY (PL_PROD_ID) REFERENCES PRODUCT(P_ID)
);

CREATE TABLE LIKE_COUNT(
LC_ID INT IDENTITY(10001,1) PRIMARY KEY,
LC_COUNT INT,
LC_PROD_ID INT
FOREIGN KEY (LC_PROD_ID) REFERENCES PRODUCT(P_ID)
);

CREATE TABLE BLOG(
B_ID INT PRIMARY KEY IDENTITY(101,1),
B_TITLE VARCHAR(250),
B_DESC VARCHAR(5000),
B_IMAGE VARCHAR(250),
B_DATE DATE DEFAULT CAST(GETDATE() AS DATE)
);

CREATE TABLE BLOG_COMMENT(
BLOG_C_ID INT PRIMARY KEY IDENTITY(1,1),
BLOG_C_NAME VARCHAR(250),
BLOG_ID INT
FOREIGN KEY (BLOG_ID) REFERENCES BLOG(B_ID),
BLOG_U_ID INT
FOREIGN KEY (BLOG_U_ID) REFERENCES USER_RECORD(U_ID)
);
INSERT INTO ROLE (R_NAME) VALUES ('Admin');
INSERT INTO ROLE (R_NAME) VALUES ('User');

CREATE TABLE CONTACT(
C_ID INT PRIMARY KEY IDENTITY(1,1),
C_MESS VARCHAR(250),
C_EMAIL VARCHAR(250),
C_NAME VARCHAR(250),
);
create table orders
(
OrderId INT PRIMARY KEY identity(1,1),
OrderDate date DEFAULT CAST(GETDATE() AS DATE),
TotalPrice TotalPrice DECIMAL(18,2),
OrderStatus VARCHAR(100),
OrderUserId INT
FOREIGN KEY(OrderUserId) REFERENCES User_Record (U_Id)
);
create table orderItems
(
OrderItemsId INT PRIMARY KEY identity(1,1),
OrderItems_OrderId INT,
OrderItems_ProdId INT,
OrderItemsQuantity INT,
FOREIGN KEY(OrderItems_OrderId) REFERENCES orders (OrderId),
FOREIGN KEY(OrderItems_ProdId) REFERENCES product (P_Id)
);
